import { createHash } from "crypto";
import { NextResponse } from "next/server";
import { createAccount, createClient, chains } from "genlayer-js";
import { TransactionStatus } from "genlayer-js/types";
import { genlayerConfig } from "@/lib/genlayer-config";
import type { ChainKey, Suggestion } from "@/lib/types";

export const maxDuration = 60;

const supportedChainKeys: ChainKey[] = ["ethereum", "base", "optimism", "arbitrum", "bnb"];
const actions = ["buy", "sell", "hold", "rebalance", "take_profit", "stop_loss", "watch"] as const;

function hash(input: unknown) {
  return `0x${createHash("sha256").update(JSON.stringify(input)).digest("hex")}`;
}

function normalizeChain(chain: string): ChainKey {
  const normalized = chain.toLowerCase();
  if (normalized.includes("base")) return "base";
  if (normalized.includes("optimism") || normalized === "op") return "optimism";
  if (normalized.includes("arbitrum") || normalized === "arb") return "arbitrum";
  if (normalized.includes("bnb") || normalized.includes("bsc")) return "bnb";
  return supportedChainKeys.includes(normalized as ChainKey) ? normalized as ChainKey : "ethereum";
}

function normalizeAction(action: string): Suggestion["action"] {
  return actions.includes(action as Suggestion["action"]) ? action as Suggestion["action"] : "watch";
}

function extractSuggestions(receipt: unknown): Suggestion[] {
  const text = JSON.stringify(receipt);
  const match = text.match(/"suggestions"\s*:\s*(\[[\s\S]*?\])/);
  if (!match) return [];
  try {
    const raw = JSON.parse(match[1]) as Array<Record<string, unknown>>;
    return raw.slice(0, 5).map((item, index) => ({
      id: `sug_${Date.now()}_${index}`,
      token: String(item.token || "UNKNOWN").toUpperCase(),
      name: String(item.token || "Unknown token").toUpperCase(),
      chain: normalizeChain(String(item.chain || "ethereum")),
      action: normalizeAction(String(item.action || "watch")),
      status: "needs_approval",
      confidence: Number(item.confidence || 0),
      risk: Number(item.risk || 100),
      amountUsd: 0,
      trigger: String(item.trigger || "GenLayer chat analysis"),
      reason: String(item.reason || "Generated by GenLayer."),
      takeProfitPct: Number(item.take_profit_pct || 0),
      stopLossPct: Number(item.stop_loss_pct || 0),
      expiresAt: new Date(Date.now() + 60 * 60 * 1000).toISOString()
    }));
  } catch {
    return [];
  }
}

function isMarketPrompt(message: string) {
  const normalized = message.toLowerCase();
  return [
    "buy",
    "sell",
    "token",
    "trade",
    "portfolio",
    "market",
    "suggest",
    "recommend",
    "rebalance",
    "profit",
    "loss",
    "risk"
  ].some((word) => normalized.includes(word));
}

function normalChatReply(message: string) {
  const normalized = message.toLowerCase();
  if (normalized.includes("hello") || normalized.includes("hi ")) {
    return "Hi. I can help you understand your portfolio setup, explain risk controls, and request GenLayer market analysis when you ask for trade or token suggestions.";
  }
  if (normalized.includes("agent wallet")) {
    return "Your agent wallet is the generated trading wallet bound to your connected owner wallet. Deposits go to the agent wallet so the executor can act within your rules.";
  }
  if (normalized.includes("deposit")) {
    return "Go to Vaults, copy the agent wallet address for the chain you want to fund, and keep native gas on that chain. The AI cannot trade without gas.";
  }
  return "I can answer setup questions directly. If you ask what to buy, sell, rebalance, or watch, I will call GenLayer and create AI proposals only after the oracle responds.";
}

export async function POST(request: Request) {
  const body = await request.json().catch(() => ({}));
  const message = String(body.message || "").trim();

  if (!message) {
    return NextResponse.json({ reply: "Send a question first." }, { status: 400 });
  }

  if (!isMarketPrompt(message)) {
    return NextResponse.json({
      reply: normalChatReply(message),
      suggestions: []
    });
  }

  const compactContext = [
    `User question: ${message}`,
    `Wallet: ${body.walletAddress || "not connected"}`,
    `Agent wallet: ${body.agentWalletAddress || "not generated"}`,
    `Profile: ${JSON.stringify(body.profile || {})}`,
    `Policy: ${JSON.stringify(body.policy || {})}`,
    "Only AI may propose trade actions. Return exactly 5 suggestions if the user asks what to buy/sell; otherwise include safe watch/hold suggestions."
  ].join("\n");

  try {
    const client = createClient({ chain: chains.studionet });
    const account = createAccount();
    const marketSnapshotHash = hash({ source: "chat", message, at: new Date().toISOString() });
    const policyHash = hash(body.policy || {});

    const txHash = await client.writeContract({
      account,
      address: genlayerConfig.contractAddress as `0x${string}`,
      functionName: "generate_suggestions",
      args: ["chat_user_segment", marketSnapshotHash, policyHash, "chat://genportai", compactContext],
      value: BigInt(0)
    });

    const receipt = await client.waitForTransactionReceipt({
      hash: txHash,
      status: TransactionStatus.ACCEPTED,
      interval: 3000,
      retries: 18
    });

    const suggestions = extractSuggestions(receipt);
    return NextResponse.json({
      reply: suggestions.length > 0
        ? `GenLayer returned ${suggestions.length} AI proposal(s). Review them in Dashboard or Approvals before any trade executes.`
        : `GenLayer transaction completed, but no structured suggestions were returned. Tx: ${txHash}`,
      txHash,
      suggestions,
      action: {
        title: "GenLayer chat analysis completed",
        status: "suggested",
        chain: suggestions[0]?.chain || "ethereum",
        token: suggestions[0]?.token || "AI",
        amountUsd: 0,
        risk: suggestions[0]?.risk || 0,
        source: "chat",
        summary: `GenLayer tx ${txHash} analyzed: ${message}`
      }
    });
  } catch (error) {
    const messageText = error instanceof Error ? error.message : "Unknown error";
    const txHash = messageText.match(/0x[a-fA-F0-9]{64}/)?.[0];
    if (txHash) {
      return NextResponse.json({
        reply: `GenLayer transaction submitted and is still running. No trade proposal has been created yet. Tx: ${txHash}`,
        txHash,
        suggestions: [],
        action: {
          title: "GenLayer chat analysis pending",
          status: "waiting",
          chain: "ethereum",
          token: "AI",
          amountUsd: 0,
          risk: 0,
          source: "chat",
          summary: `Waiting for GenLayer tx ${txHash} to reach accepted status.`
        }
      }, { status: 202 });
    }
    return NextResponse.json({
      reply: `GenLayer call failed, so no trade proposal was created. ${messageText}`,
      suggestions: []
    }, { status: 502 });
  }
}
